version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: my-postgres
    restart: always
    env_file:
      - ./backend/.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"

  app:
    build: ./backend
    container_name: springboot-app
    ports:
      - "8080:8080"
    env_file:
      - ./backend/.env
    depends_on:
      - postgres
      - redis

volumes:
  postgres_data:
